In [12]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google'

In [ ]:
!git clone https://github.com/rafaseto/PIBIC-AnaliseDados.git

fatal: destination path 'PIBIC-AnaliseDados' already exists and is not an empty directory.

In [ ]:
%cd PIBIC-AnaliseDados

c:\Users\rafae\Documents\somebooks\College\PIBIC\Rafael-AnaliseDados\PIBIC-AnaliseDados

In [ ]:
import pip

In [ ]:
!pip install dlisio

Requirement already satisfied: dlisio in c:\users\rafae\appdata\local\programs\python\python310\lib\site-packages (1.0.1)
Requirement already satisfied: numpy<2.0 in c:\users\rafae\appdata\local\programs\python\python310\lib\site-packages (from dlisio) (1.26.0)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
from dlisio import dlis
import pandas as pd

In [2]:
# A função 'glob' do módulo 'glob' é usada para procurar todos os arquivos em um diretório com determinada extensão
import glob

In [3]:
dli = []        # Conterá os arquivos lógicos
filenames = []  # Conterá os caminhos dos arquivos dlis
pocos = []      # Conterá strings identificadoras de 9 caracteres, tipo '3-CP-1847'
charId_inicio, charId_fim = 5, 14   # Índices de início e fim da substring identificadora do poço

# Utilizando a função 'glob' do módulo 'glob' para procurar todos os arquivos com extensão DLIS em 'Data'
for file in glob.glob(r'**/Data' + "/*.dlis", recursive=True):
    # Carregando os arquivos dlis com 'load' e armazenando-os em 'leitura'
    # 'tail' recebe valores restantes, caso a função retorne mais de uma peça de informação
    leitura, *tail = dlis.load(f'{file}')
    pocos.append(file[charId_inicio : charId_fim])    # armazenando identificadores do tipo '3-CP-XXXX'
    filenames.append(file)      # armazenando o caminho dos arquivos dlis
    dli.append(leitura)         # armazenando os arquivos lógicos carregados com 'load'

In [4]:
# Criando um dicionário para associar nomes aos elementos de dli
dli_dict = {
    '1847': dli[0],
    '1848': dli[1],
    '1851': dli[2],
    '1853': dli[3],
    '1855': dli[4],
    '1857': dli[5]
}

In [5]:
dli_dict['1847'].describe()

------------
Logical File
------------
Description : LogicalFile(GEOLOAD.1)
Frames      : 1
Channels    : 21

Known objects
--
PARAMETER   : 167
FILE-HEADER : 1
TOOL        : 1
CHANNEL     : 21
FRAME       : 1
ORIGIN      : 1
COMMENT     : 2
NO-FORMAT   : 1

Unknown objects
--
280-FRAMESTEP-INFO : 1

In [6]:
dlis_df = []    # Conterá os dlis_df_dict respectivos aos poços

# Curvas de perfis que não serão utilizadas
curvas_nao_utilizadas = ['WF11', 'AHV', 'AHVT', 'BHV', 'BHVT', 'CS', 'FCPS', 'HDCN', 'HMCN', 'ITT', 'ITTT', 'LSPD', 'MMK', 'NCPS', 'SP']

# Iterando sobre os arquivos lógicos de todos os poços (que estão armazenados em 'dli_dict'),
# '.values()' se refere aos valores do dicionário (não às chaves)
for poco in dli_dict.values():
    try:
        # Armazenando as curvas que serão utilizadas em uma lista
        curvas_utilizadas = [
            channel.name                                    # Os elementos da lista serão os nomes das curvas
            for channel in poco.channels                    # As curvas são acessadas por meio de 'poco.channels'
            if channel.name not in curvas_nao_utilizadas    # As curvas que não utilizaremos não serão armazenadas na lista
        ]


        curvas = poco.frames[0].curves()

        # Criando um pandas dataframe do poço respectivo à atual iteração e armazenando o mesmo em dlis_df
        dlis_df.append(pd.DataFrame(curvas[curvas_utilizadas]))
    except:
        pass

In [7]:
# Criando um dicionário para associar nomes aos elementos de dlis_df
dlis_df_dict = {
    '1847' : dlis_df[0],
    '1848' : dlis_df[1],
    '1851' : dlis_df[2],
    '1853' : dlis_df[3],
    '1855' : dlis_df[4],
    '1857' : dlis_df[5]
}

In [8]:
dlis_df_dict['1847']

,TDEP,GR,TENS,BS,NPHI,CALI,RHOB,DRHO,PE,HDRS,HMRS,DTC
0,374.899994,-999.250000,345.178406,8.5,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25
1,374.799994,-999.250000,346.090210,8.5,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25
2,374.699994,-999.250000,348.874512,8.5,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25
3,374.599994,-999.250000,348.379608,8.5,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25
4,374.499994,-999.250000,349.917908,8.5,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25
...,...,...,...,...,...,...,...,...,...,...,...,...
3595,15.399989,55.795601,910.639893,8.5,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25
3596,15.299989,52.518200,910.807007,8.5,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25
3597,15.199989,48.504501,909.179626,8.5,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25
3598,15.099989,45.021198,909.942383,8.5,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25
3599,14.999989,45.702099,909.483582,8.5,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25

In [9]:
from aux_datapreprocess import *

## Remoção de Colunas

In [10]:
colunas_para_remover = ['CALI', 'RHOB', 'DRHO', 'PE', 'HDRS', 'HMRS', 'DTC']
dlis_df_dict['1847'] = remove_colunas(dlis_df_dict['1847'], colunas_para_remover)

In [11]:
dlis_df_dict['1847']

            TDEP          GR        TENS   BS    NPHI
0     374.899994 -999.250000  345.178406  8.5 -999.25
1     374.799994 -999.250000  346.090210  8.5 -999.25
2     374.699994 -999.250000  348.874512  8.5 -999.25
3     374.599994 -999.250000  348.379608  8.5 -999.25
4     374.499994 -999.250000  349.917908  8.5 -999.25
...          ...         ...         ...  ...     ...
3595   15.399989   55.795601  910.639893  8.5 -999.25
3596   15.299989   52.518200  910.807007  8.5 -999.25
3597   15.199989   48.504501  909.179626  8.5 -999.25
3598   15.099989   45.021198  909.942383  8.5 -999.25
3599   14.999989   45.702099  909.483582  8.5 -999.25

[3600 rows x 5 columns]

## Renomeação de Colunas

In [12]:
dlis_df_dict['1847'] = renomeiaColuna(dlis_df_dict['1847'], "GR", "gamma-ray")

In [13]:
dlis_df_dict['1847']

            TDEP   gamma-ray        TENS   BS    NPHI
0     374.899994 -999.250000  345.178406  8.5 -999.25
1     374.799994 -999.250000  346.090210  8.5 -999.25
2     374.699994 -999.250000  348.874512  8.5 -999.25
3     374.599994 -999.250000  348.379608  8.5 -999.25
4     374.499994 -999.250000  349.917908  8.5 -999.25
...          ...         ...         ...  ...     ...
3595   15.399989   55.795601  910.639893  8.5 -999.25
3596   15.299989   52.518200  910.807007  8.5 -999.25
3597   15.199989   48.504501  909.179626  8.5 -999.25
3598   15.099989   45.021198  909.942383  8.5 -999.25
3599   14.999989   45.702099  909.483582  8.5 -999.25

[3600 rows x 5 columns]

## Transformação NPHI

In [14]:
dlis_df_dict['1853']

,TDEP,DTC,HDRS,HMRS,GR,CALI,NPHI,RHOB,DRHO,PE,TENS,BSZ
0,319.000000,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,1065.134399,8.50
1,318.900000,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,1340.839844,8.50
2,318.800000,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,1580.882080,8.50
3,318.700000,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,1798.774292,8.50
4,318.600000,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,1948.277588,8.50
...,...,...,...,...,...,...,...,...,...,...,...,...
3102,8.799995,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.250000,-999.25
3103,8.699995,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.250000,-999.25
3104,8.599995,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.250000,-999.25
3105,8.499995,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.250000,-999.25
3106,8.399995,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.25,-999.250000,-999.25

In [15]:
nphi_transform(dlis_df_dict, ['1847', '1853'])

In [16]:
dlis_df_dict['1853']

,TDEP,DTC,HDRS,HMRS,GR,CALI,NPHI,RHOB,DRHO,PE,TENS,BSZ
0,319.000000,-999.25,-999.25,-999.25,-999.25,-999.25,-99925.0,-999.25,-999.25,-999.25,1065.134399,8.50
1,318.900000,-999.25,-999.25,-999.25,-999.25,-999.25,-99925.0,-999.25,-999.25,-999.25,1340.839844,8.50
2,318.800000,-999.25,-999.25,-999.25,-999.25,-999.25,-99925.0,-999.25,-999.25,-999.25,1580.882080,8.50
3,318.700000,-999.25,-999.25,-999.25,-999.25,-999.25,-99925.0,-999.25,-999.25,-999.25,1798.774292,8.50
4,318.600000,-999.25,-999.25,-999.25,-999.25,-999.25,-99925.0,-999.25,-999.25,-999.25,1948.277588,8.50
...,...,...,...,...,...,...,...,...,...,...,...,...
3102,8.799995,-999.25,-999.25,-999.25,-999.25,-999.25,-99925.0,-999.25,-999.25,-999.25,-999.250000,-999.25
3103,8.699995,-999.25,-999.25,-999.25,-999.25,-999.25,-99925.0,-999.25,-999.25,-999.25,-999.250000,-999.25
3104,8.599995,-999.25,-999.25,-999.25,-999.25,-999.25,-99925.0,-999.25,-999.25,-999.25,-999.250000,-999.25
3105,8.499995,-999.25,-999.25,-999.25,-999.25,-999.25,-99925.0,-999.25,-999.25,-999.25,-999.250000,-999.25
3106,8.399995,-999.25,-999.25,-999.25,-999.25,-999.25,-99925.0,-999.25,-999.25,-999.25,-999.250000,-999.25

## Remoção de Pontos com Falha

In [17]:
pontos_com_falha = {
    '1847': [250, 360],
    '1848': [75, 210],
    '1851': [60, 260],
    '1853': [90, 300],
    '1855': [64, 215],
    '1857': [90, 320]
}

In [18]:
#dlis_df_dict['1847'].drop(dlis_df_dict['1847'][dlis_df_dict['1847']['TDEP'] > 300].index)

In [19]:
# Chamando a função
remove_pontos_com_falha(dlis_df_dict, pontos_com_falha)

In [24]:
dlis_df_dict['1847']

            TDEP  gamma-ray         TENS   BS       NPHI
149   359.999994  83.756798  1199.074097  8.5  21.250000
150   359.899994  76.283600  1203.497925  8.5  19.070000
151   359.799994  74.953598  1206.341675  8.5  19.270000
152   359.699994  73.211998  1205.656372  8.5  19.639999
153   359.599994  76.093597  1204.261230  8.5  20.510000
...          ...        ...          ...  ...        ...
1244  250.499992  44.063301  1139.797852  8.5  14.370001
1245  250.399992  50.523201  1129.405273  8.5  17.039999
1246  250.299992  54.085602  1132.142456  8.5  18.129999
1247  250.199992  56.096401  1136.727051  8.5  20.170000
1248  250.099992  63.949600  1136.542480  8.5  24.580000

[1100 rows x 5 columns]